(define (problem hanoi-5-disks-3-pegs)
  (:domain hanoi-ff)
  (:objects 
    disk1 disk2 disk3 disk4 disk5 - disk
    peg1 peg2 peg3 - peg)
  (:init
    (on disk5 peg1)
    (on disk4 disk5)
    (on disk3 disk4)
    (on disk2 disk3)
    (on disk1 disk2)
    (clear disk1)
    (clear peg2)
    (clear peg3)
    (smaller disk1 disk2)
    (smaller disk1 disk3)
    (smaller disk1 disk4)
    (smaller disk1 disk5)
    (smaller disk2 disk3)
    (smaller disk2 disk4)
    (smaller disk2 disk5)
    (smaller disk3 disk4)
    (smaller disk3 disk5)
    (smaller disk4 disk5)
  )
  (:goal (and
    (on disk5 peg3)
    (on disk4 disk5)
    (on disk3 disk4)
    (on disk2 disk3)
    (on disk1 disk2)
  ))
)
